# Generated by Django 5.1.7 on 2025-03-19 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='logs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='excel/')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
                ('timestamp', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('protocol', models.CharField(max_length=20)),
                ('status_code', models.IntegerField()),
                ('response_size', models.IntegerField()),
                ('referrer', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.CharField(max_length=255)),
                ('log_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='dashboard.logfile')),
            ],
        ),
        migrations.CreateModel(
            name='QueryParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='dashboard.logentry')),
            ],
        ),
    ]
