# Generated by Django 5.1.7 on 2025-03-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logfile',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='logentry',
            name='ip_address',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='method',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='path',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='status_code',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='timestamp',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='logfile',
            name='processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='logfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='queryparameter',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['log_file', 'status_code'], name='dashboard_l_log_fil_98b3d0_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['log_file', 'method'], name='dashboard_l_log_fil_624e18_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['log_file', 'timestamp'], name='dashboard_l_log_fil_0feb70_idx'),
        ),
        migrations.AddIndex(
            model_name='logfile',
            index=models.Index(fields=['uploaded_at'], name='dashboard_l_uploade_326827_idx'),
        ),
        migrations.AddIndex(
            model_name='logfile',
            index=models.Index(fields=['processed'], name='dashboard_l_process_837dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='queryparameter',
            index=models.Index(fields=['log_entry', 'name'], name='dashboard_q_log_ent_c75c04_idx'),
        ),
        migrations.AddIndex(
            model_name='queryparameter',
            index=models.Index(fields=['name', 'value'], name='dashboard_q_name_f8f83a_idx'),
        ),
    ]
